/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppAddItem {}
  interface AppDetails {
    'match': MatchResults;
  }
  interface AppListItem {
    'completed': any;
    'itemId': any;
    'itemName': any;
  }
  interface AppLoader {}
  interface AppRoot {}
  interface AppTimer {}
  interface AppTodolist {
    'myMethod': () => Promise<number>;
    'myMethod2': () => Promise<number>;
    'myMethod3': () => Promise<void>;
  }
}

declare global {


  interface HTMLAppAddItemElement extends Components.AppAddItem, HTMLStencilElement {}
  var HTMLAppAddItemElement: {
    prototype: HTMLAppAddItemElement;
    new (): HTMLAppAddItemElement;
  };

  interface HTMLAppDetailsElement extends Components.AppDetails, HTMLStencilElement {}
  var HTMLAppDetailsElement: {
    prototype: HTMLAppDetailsElement;
    new (): HTMLAppDetailsElement;
  };

  interface HTMLAppListItemElement extends Components.AppListItem, HTMLStencilElement {}
  var HTMLAppListItemElement: {
    prototype: HTMLAppListItemElement;
    new (): HTMLAppListItemElement;
  };

  interface HTMLAppLoaderElement extends Components.AppLoader, HTMLStencilElement {}
  var HTMLAppLoaderElement: {
    prototype: HTMLAppLoaderElement;
    new (): HTMLAppLoaderElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppTimerElement extends Components.AppTimer, HTMLStencilElement {}
  var HTMLAppTimerElement: {
    prototype: HTMLAppTimerElement;
    new (): HTMLAppTimerElement;
  };

  interface HTMLAppTodolistElement extends Components.AppTodolist, HTMLStencilElement {}
  var HTMLAppTodolistElement: {
    prototype: HTMLAppTodolistElement;
    new (): HTMLAppTodolistElement;
  };
  interface HTMLElementTagNameMap {
    'app-add-item': HTMLAppAddItemElement;
    'app-details': HTMLAppDetailsElement;
    'app-list-item': HTMLAppListItemElement;
    'app-loader': HTMLAppLoaderElement;
    'app-root': HTMLAppRootElement;
    'app-timer': HTMLAppTimerElement;
    'app-todolist': HTMLAppTodolistElement;
  }
}

declare namespace LocalJSX {
  interface AppAddItem extends JSXBase.HTMLAttributes<HTMLAppAddItemElement> {
    'onAddItem'?: (event: CustomEvent<any>) => void;
  }
  interface AppDetails extends JSXBase.HTMLAttributes<HTMLAppDetailsElement> {
    'match'?: MatchResults;
  }
  interface AppListItem extends JSXBase.HTMLAttributes<HTMLAppListItemElement> {
    'completed'?: any;
    'itemId'?: any;
    'itemName'?: any;
    'onTodoCompleted'?: (event: CustomEvent<any>) => void;
  }
  interface AppLoader extends JSXBase.HTMLAttributes<HTMLAppLoaderElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppTimer extends JSXBase.HTMLAttributes<HTMLAppTimerElement> {}
  interface AppTodolist extends JSXBase.HTMLAttributes<HTMLAppTodolistElement> {}

  interface IntrinsicElements {
    'app-add-item': AppAddItem;
    'app-details': AppDetails;
    'app-list-item': AppListItem;
    'app-loader': AppLoader;
    'app-root': AppRoot;
    'app-timer': AppTimer;
    'app-todolist': AppTodolist;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


